### ISSUE TITLE
Procedural generation (ingame)

### ISSUE THREAD

**Issue by havi05** [awkwardpolygons/awkpol1#10]
**Is your feature request related to a problem? Please describe.**
I don't know how i can make 3d procedural terrain (and cave) generation. I found your addon and it looks really great, so this generation would be really helpful for big games.

**Describe the solution you'd like**
A procedural terrain (later also cave) generation ingame.

**Describe alternatives you've considered**
No alternatives for this request.

**Additional context**
This is a really big feature request and I don't know much about terrain generation, but I will try to help.

**Comment by arccoza** [comment]
Thanks for the suggestion. I'm currently working on a new version of Cartographer that will be a lot more flexible, you should be able to mix and match both procedural and hand crafted areas.

Caves are another matter (because this is heightmap based terrain), and I've had people ask how to do it before. It depends on the perspective in your game, if you only need to render the floor of a cave, say in a 3rd person or top-down game, then caves are just normal terrain sculpted to look like tunnels etc. If you need a cave roof, for a 1st person view, then you'll probably want another terrain sculpted "upside down".

Keep an eye out for the next release, it's a major rework, and will hopefully have some nice new features.

**Comment by havi05** [comment]
Thank you very much!

**Comment by havi05** [comment]
I have a 1st person view, so I would need the complicated way.
